### ISSUE TITLE
Ask for paper

### ISSUE THREAD

**Issue by ierosodin** [savinienb/Matwo-CapsNet#1]
Happy to hear that there is a new paper about capsule network in object segmentation task.
However, I found that the link of your paper is not work. Could I ask for a copy of your work?
Or you can send me by email: ierosodin@gmail.com
Thanks.

**Comment by savinienb** [comment]
Hi,

The paper will be uploaded later on.
In the meantime, I'll send you a preprint version of the manuscript.

Cheers.

**Comment by ierosodin** [comment]
Thanks, I got the mail!

B.R.
